[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python main.py"

# Environment variables
[variables]
PORT = "8000"
PYTHON_VERSION = "3.9"
NIXPACKS_PYTHON_VERSION = "3.9"
INSIGHTFACE_MODEL_PATH = "/root/.insightface/models"
INSIGHTFACE_PROVIDER = "CPUExecutionProvider"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PORT = "5174"
PYTHON_VERSION = "3.9"
NIXPACKS_PYTHON_VERSION = "3.9"