[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python api/app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PORT = "5174"
PYTHON_VERSION = "3.9"
NIXPACKS_PYTHON_VERSION = "3.9"